### ISSUE TITLE
Feature 1: User can register an account

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Feature 1: User can register an account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will enter a username, password, and click the `Register` button if they want to create an account. If the user wants to sign in as a guest, they will click the `Sign in` link where there is an option to do so. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

### Mobile
![Screen Shot 2022-07-18 at 1 07 35 PM](https://user-images.githubusercontent.com/67080126/179608251-4cd39d26-6217-410a-bfd7-bb6d6f08f43d.png)
### Desktop
![Screen Shot 2022-07-18 at 1 12 49 PM](https://user-images.githubusercontent.com/67080126/179609055-9d3a02d1-923f-478e-bd01-912b99632696.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to the exported create.sql from db designer

### ☁️ Server

- [x] Update `server/index.js` to handle POST requests for new usernames and passwords.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a `Header` component
- [x] Create a `PageContainer` component
- [x] Create an `AuthForm` component
  - [x] Set up a handleSubmit event handler to send a POST request to API for sign-up

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
