### ISSUE TITLE
Feature 10: User can view their itineraries

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their itineraries

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click on the `Itineraries` option from the `AppDrawer` component to view their itineraries. The user can then click on an itinerary to see its details.  If they have no itineraries, it will display the message "Sorry, no itineraries found.".

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

### Mobile
![Screen Shot 2022-08-18 at 9 26 41 PM](https://user-images.githubusercontent.com/67080126/185542831-840f2f71-f141-4cc7-ae51-4d326996d9d4.png)
### Desktop
![Screen Shot 2022-08-18 at 9 36 34 PM](https://user-images.githubusercontent.com/67080126/185543795-ac511fc7-40d1-479a-bff8-c7c1b66893e8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create path /api/itineraries to handle GET requests in server/index.js
- [x] Create path /api/itineraries-events to handle GET requests in server/index.js
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create an `Itineraries` and `ItineraryCard` component to display a list of itineraries
- [x] Create an `ItinereraryDetails` component to display the details of an itinerary

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
