### ISSUE TITLE
Feature 11: User can add an event to an itinerary

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add an event to an itinerary.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click the `Add an event` menu to add an event to their itinerary. If the event is already in their itinerary, it will be disabled from the menu.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

### Mobile
![Screen Shot 2022-08-28 at 4 27 05 PM](https://user-images.githubusercontent.com/67080126/187099047-af491b5d-9149-44ee-ac79-79c7a28b357e.png)
### Desktop
![Screen Shot 2022-08-28 at 4 28 32 PM](https://user-images.githubusercontent.com/67080126/187099094-9b942c40-da53-42c3-b242-71feaa0c6c61.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a `Select` component that will fetch the user's bookmarks and have the functionality to add bookmarks as events to their itinerary

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
