### ISSUE TITLE
Feature 12: User can delete an event from an itinerary

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete an event from an itinerary.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click the trash icon from a specific `EventCard` to delete an event from their itinerary.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

### Mobile
![Screen Shot 2022-08-29 at 7 05 04 PM](https://user-images.githubusercontent.com/67080126/187332303-db8d3e6f-37de-4fd0-9122-d0b636388ef3.png)
### Desktop
![Screen Shot 2022-08-29 at 7 03 17 PM](https://user-images.githubusercontent.com/67080126/187332121-aac397ec-6911-44bb-8f62-641bf57ec46d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create path `/api/itinerary-events` to handle DELETE requests in server/index.js
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a `handleDeleteItineraryEvent` function to DELETE data from the `/api/itinerary-events` path

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
