### ISSUE TITLE
Feature 13: User can delete an itinerary

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete an itinerary.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click the trash icon which will display a modal that asks `Are you sure you want to delete {itineraryName}?` with a `Yes, delete it` button and a `No, keep it` button. Both buttons will return the user back to the itineraries page where the only difference is if the `Yes, delete it` button is clicked, that itinerary is removed.   

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

### Mobile
![Screen Shot 2022-09-18 at 10 25 38 AM](https://user-images.githubusercontent.com/67080126/190920387-33c98108-8fed-44ff-b0cd-93f11915aa5b.png)
### Desktop
![Screen Shot 2022-09-18 at 10 27 47 AM](https://user-images.githubusercontent.com/67080126/190920459-98f54683-23ff-46a7-a810-038626fb64ff.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create endpoints `/api/itinerary-events/itinerary-id/:itineraryId` and `/api/itineraries/user-id/itinerary-id/:itineraryId` to handle DELETE requests in server/index.js
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a `DeleteItineraryModal` component with functionality to delete an itinerary

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
