### ISSUE TITLE
Refactor: Display error messages for issue 1 and 2 

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#18]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

### ☁️ Server

- [x] Update `server/index.js` to handle errors for duplicate username

### ⚡ Client

- [x] Update `AuthForm` component to display error messages when res.status codes are 401 or 409

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
