### ISSUE TITLE
Feature 2: User can sign in to their account

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in to their account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user has an account, they will enter their username, password, and click the `Sign In` button to log in to their account. The user also has the option to click on the `Guest` button if they want to log in as a guest. If they want to create an account, they can click on the `Register` link.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

### Mobile
![Screen Shot 2022-07-18 at 8 27 06 PM](https://user-images.githubusercontent.com/67080126/179658174-4c456a2e-0a67-4561-99f0-59e6339f541b.png)
### Desktop
![Screen Shot 2022-07-18 at 8 24 48 PM](https://user-images.githubusercontent.com/67080126/179657958-8ccd1f61-0e02-4644-acc9-df9a6a99c1bd.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to insert guest user login info

### ☁️ Server

- [x] Update `server/index.js` to respond to POST requests for user sign-in
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create `Redirect` component
- [x] Create `AppContext` utility function
- [x] Update `App`, `Home`, `Auth`, and `AuthForm` component with appropriate handlers to send a POST request to API for sign in

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
