### ISSUE TITLE
Feature 3: User can sign out of their account

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out of their account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will click on the hamburger menu icon and click on the `Sign Out` option to sign out of their account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

### Mobile
<img width="206" alt="Screen Shot 2022-07-20 at 2 15 31 PM" src="https://user-images.githubusercontent.com/67080126/180083710-74234d72-d06f-45d9-bce9-535bd4974a87.png">

### Desktop
<img width="634" alt="Screen Shot 2022-07-20 at 2 30 44 PM" src="https://user-images.githubusercontent.com/67080126/180085866-a1178a8f-56be-43cb-baa9-34dc8baaf329.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create `AppDrawer` component to have a drop down menu that has an option to sign out  with a  handleSignOut event handler

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
