### ISSUE TITLE
Feature 4: User can search for an event by location

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for an event by location.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will enter an event and a location, then click the search icon. This will send them to the results page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

### Mobile
<img width="206" alt="Screen Shot 2022-07-21 at 4 12 17 PM" src="https://user-images.githubusercontent.com/67080126/180330165-71c5c8c0-4eda-4166-8c81-d398bda9c549.png">

### Desktop
<img width="633" alt="Screen Shot 2022-07-21 at 4 16 47 PM" src="https://user-images.githubusercontent.com/67080126/180330543-bbf3f743-b9bd-40bc-8edc-ab11818f775c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to respond to GET requests to route `/api/search-yelp`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update `Home` component with search bar and appropriate handlers

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
