### ISSUE TITLE
Feature 5: User can view search results

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view search results.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the search has been completed, the user will see the `results` page with either no results or card(s) based on the search term and location. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

### Mobile
![Screen Shot 2022-07-26 at 9 02 53 PM](https://user-images.githubusercontent.com/67080126/181158337-37a832bb-7940-4890-aa24-cb1028a581a0.png)

### Desktop
![Screen Shot 2022-07-26 at 9 05 54 PM](https://user-images.githubusercontent.com/67080126/181158952-5c895435-c860-4d96-a774-ef04ba762155.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` with endpoint `/api/search-yelp` to handle `no result` errors
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a `Results` component
- [x] Implement fetch GET request to server endpoint `/api/search-yelp/?term=${term}&location=${location}`
- [x]  Create a `Card` component that displays an event received from the `Yelp API`

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
