### ISSUE TITLE
Feature 6: User can bookmark an event 

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can bookmark an event.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click on the bookmark icon to add or delete an event to their `Bookmarks` which will change the color of the icon from white to black (add) or black to white (delete).

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

### Mobile
![Screen Shot 2022-07-30 at 2 26 31 PM](https://user-images.githubusercontent.com/67080126/181996686-5457a422-9477-4edf-99d5-671ea84a3e01.png)
### Desktop
![Screen Shot 2022-07-30 at 2 28 16 PM](https://user-images.githubusercontent.com/67080126/181996719-27252386-b89a-460d-b3d2-6a0a288434f9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Revise `schema.sql` to have appropriate fields

### ☁️ Server

- [x] Create `authorizationMiddleware`  and add it to `server/index.js`
- [x] Create `/api/bookmarks` route in `server/index.js` to handle POST requests 
- [x] Create `/api/bookmarks` route in `server/index.js` to handle GET and DELETE requests
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update `EventCard` and `Results` component to handle the addition, deletion, and persistence of bookmarks

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
