### ISSUE TITLE
Feature 7: User can view their bookmarks

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their bookmarks.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click on the `Bookmarks` option from the `AppDrawer` component to view their bookmarks. If they have no bookmarks, it will display the message "Sorry, no bookmarks found.".

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

### Mobile
![Screen Shot 2022-08-02 at 10 51 01 PM](https://user-images.githubusercontent.com/67080126/182533893-926b96f3-58a4-43f9-bb80-b7919f098c82.png)
### Desktop
![Screen Shot 2022-08-02 at 10 48 06 PM](https://user-images.githubusercontent.com/67080126/182533565-cd465c34-656e-4cac-84ab-589ad7b125fb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a `Bookmarks` component that will fetch bookmarks from the server/db and display fetched bookmarks

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
