### ISSUE TITLE
Feature 8: User can delete a bookmark

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a bookmark.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click on the `Delete` option from the `ellipses icon` to delete a bookmark. The `Bookmark` page will then display their updated bookmarks.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

### Mobile
![Screen Shot 2022-08-03 at 6 07 41 PM](https://user-images.githubusercontent.com/67080126/182741307-fbd90b06-d34b-4396-a801-b53596715e46.png)
### Desktop
![Screen Shot 2022-08-03 at 6 10 59 PM](https://user-images.githubusercontent.com/67080126/182741625-1292a4e9-6675-4e84-a58b-cf9b5e0c1fb0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a `handleDeleteBookmark` function in `Bookmarks` page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
