### ISSUE TITLE
Feature 9: User can create an itinerary from a bookmarked event

### ISSUE THREAD

**Issue by mmoncera** [mmoncera/evently#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an itinerary from a bookmarked event.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click on the `Create Itinerary` option from the ellipsis menu icon which will go to the `CreateItinerary` page. The user can enter the name and date of their itinerary and upon clicking the `Save` button it will save the provided information to their itineraries and change to the `Itineraries` page. The user can also click on the `Cancel` button to go back to the `Bookmarks` page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

### Mobile
![Screen Shot 2022-08-08 at 9 37 51 PM](https://user-images.githubusercontent.com/67080126/183565471-1b2af16c-485d-4c14-954b-30d1bad46b94.png)
### Desktop
![Screen Shot 2022-08-08 at 9 40 51 PM](https://user-images.githubusercontent.com/67080126/183565774-34efaaf8-31c7-4eef-aead-b9b3ee496c36.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have appropriate fields

### ☁️ Server

- [x] Create paths `/api/itineraries` and `/api/itinerary-events` to handle POST requests in `server/index.js` 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a `CreateItinerary` component that has a `HandleSubmit` function to POST data to  `/api/itineraries` and `/api/itinerary-events` paths.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
